/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_AvailableColumnsPanel
#define HEADER_AvailableColumnsPanel
/*
htop - AvailableColumnsPanel.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Panel.h"
#include "FieldData.h"

typedef struct AvailableColumnsPanel_ {
   Panel super;
   Panel* columns;
   const FieldData *field_data;
   unsigned int nfields;
} AvailableColumnsPanel;

#ifdef DISK_STATS
#endif

extern PanelClass AvailableColumnsPanel_class;

AvailableColumnsPanel* AvailableColumnsPanel_new(Panel* columns, bool disk_mode);

#endif
