/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_htop
#define HEADER_htop
/*
htop - htop.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#if defined HAVE_GETOPT_H && defined HAVE_GETOPT_LONG
#endif

//#link m

 
// ----------------------------------------


int main(int argc, char** argv);

#endif
