/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_UptimeMeter
#define HEADER_UptimeMeter
/*
htop - UptimeMeter.h
(C) 2004-2011 Hisham H. Muhammad
Copyright 2015-2024 Rivoreo
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#ifdef HAVE_UTMPX
#endif
#if defined HAVE_UTMPX || defined HAVE_CLOCK_GETTIME
#endif

#include "Meter.h"

extern int UptimeMeter_attributes[];

#ifdef HAVE_CLOCK_GETTIME
// CLOCK_UPTIME excludes suspend time, available since kFreeBSD 7.0
// CLOCK_BOOTTIME includes suspend time, available since Linux 2.6.39
// CLOCK_MONOTONIC_RAW excludes suspend time, available since Linux 2.6.28
#ifndef CLOCK_UPTIME
#ifdef CLOCK_BOOTTIME
#define CLOCK_UPTIME CLOCK_BOOTTIME
#elif defined CLOCK_MONOTONIC_RAW && defined __linux__
#define CLOCK_UPTIME CLOCK_MONOTONIC_RAW
#endif
#endif
#endif

extern MeterClass UptimeMeter_class;

#endif
