/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_openbsd_Platform
#define HEADER_openbsd_Platform
/*
htop - openbsd/Platform.h
(C) 2014 Hisham H. Muhammad
(C) 2015 Michael McConville
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#ifdef SAFE_TO_DEFINE_KERNEL
#define _KERNEL
#endif
#ifdef SAFE_TO_DEFINE_KERNEL
#undef _KERNEL
#endif

#include "bsd/Platform.h"
#include "Action.h"
#include "BatteryMeter.h"
#include "SignalsPanel.h"

#define PLATFORM_SUPPORT_PROCESS_O_STATE

extern ProcessFieldData Process_fields[];


extern ProcessField Platform_defaultFields[];

extern int Platform_numberOfFields;

/*
 * See /usr/include/sys/signal.h
 */
extern const SignalItem Platform_signals[];

extern const unsigned int Platform_numberOfSignals;

void Platform_setBindings(Htop_Action* keys);

extern MeterClass* Platform_meterTypes[];

void Platform_getLoadAverage(double* one, double* five, double* fifteen);

int Platform_getMaxPid();

double Platform_setCPUValues(Meter *meter, int cpu);

void Platform_setMemoryValues(Meter *meter);

/*
 * Copyright (c) 1994 Thorsten Lockert <tholo@sigmasoft.com>
 * All rights reserved.
 *
 * Based on OpenBSD's top(1)
 */
void Platform_setSwapValues(Meter *meter);

char **Platform_getProcessArgv(const Process *proc);

char **Platform_getProcessEnvv(const Process *proc);

bool Platform_haveSwap();

#endif
