/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_darwin_DarwinPrivilegeCheck
#define HEADER_darwin_DarwinPrivilegeCheck
/*
htop - darwin/DarwinPrivilegeCheck.h
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/
#include <stdbool.h>

bool DarwinPrivilegeCheck_isRoot(void);

bool DarwinPrivilegeCheck_requestRoot(void);

#endif
