/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_darwin_Platform
#define HEADER_darwin_Platform
/*
htop - darwin/Platform.h
(C) 2014 Hisham H. Muhammad
(C) 2015 David C. Hunt
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "bsd/Platform.h"
#include "Action.h"
#include "SignalsPanel.h"
#include "CPUMeter.h"
#include "BatteryMeter.h"
#include "DarwinProcess.h"

#ifndef CLAMP
#define CLAMP(x,low,high) (((x)>(high))?(high):(((x)<(low))?(low):(x)))
#endif

extern ProcessField Platform_defaultFields[];

extern const SignalItem Platform_signals[];

extern const unsigned int Platform_numberOfSignals;

extern ProcessFieldData Process_fields[];

extern MeterClass* Platform_meterTypes[];

void Platform_setBindings(Htop_Action* keys);

extern int Platform_numberOfFields;

void Platform_getLoadAverage(double* one, double* five, double* fifteen);

int Platform_getMaxPid();

extern ProcessPidColumn Process_pidColumns[];

double Platform_updateCPUValues(Meter *mtr, int cpu);

void Platform_updateMemoryValues(Meter *mtr);

void Platform_updateSwapValues(Meter *mtr);

char **Platform_getProcessArgv(const Process *proc);

char **Platform_getProcessEnvv(const Process *proc);

bool Platform_haveSwap();

#endif
