/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_aix_Platform
#define HEADER_aix_Platform
/*
htop - aix/Platform.h
(C) 2014 Hisham H. Muhammad
(C) 2015 David C. Hunt
(C) 2018 Calvin Buckley
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#ifndef __PASE__
#endif

#define _LARGE_FILE_API

#include "Action.h"
#include "BatteryMeter.h"
#include "SignalsPanel.h"
#include "AixProcess.h"

// Used for the load average.
#include <sys/kinfo.h>
// AIX doesn't define this function for userland headers, but it's in libc
extern int getkerninfo(int, char*, int*, int32long64_t);

#ifndef CLAMP
#define CLAMP(x,low,high) (((x)>(high))?(high):(((x)<(low))?(low):(x)))
#endif

extern const SignalItem Platform_signals[];

extern const unsigned int Platform_numberOfSignals;

extern ProcessField Platform_defaultFields[];

extern MeterClass* Platform_meterTypes[];

void Platform_setBindings(Htop_Action* keys);

extern const unsigned int Platform_numberOfFields;

int Platform_getUptime();

void Platform_getLoadAverage(double* one, double* five, double* fifteen);

int Platform_getMaxPid();

double Platform_updateCPUValues(Meter *meter, int cpu);

void Platform_updateMemoryValues(Meter *meter);

void Platform_updateSwapValues(Meter *meter);

char **Platform_getProcessArgv(const Process *proc);

char **Platform_getProcessEnvv(const Process *proc);

bool Platform_haveSwap();

#endif
