/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_dragonflybsd_Platform
#define HEADER_dragonflybsd_Platform
/**
htop - dragonflybsd/Platform.h
(C) 2014 Hisham H. Muhammad
(C) 2017 Diederik de Groot
Copyright 2022-2026 Rivoreo
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include <bsd/Platform.h>
#include <Action.h>
#include <BatteryMeter.h>
#include <SignalsPanel.h>

#define PLATFORM_HAVE_BUFFERS_MEMORY_CLASS

typedef struct {
	int hw_physmem_mib[2];
	int vm_stats_vm_v_page_count_mib[4];
	int vm_stats_vm_v_wire_count_mib[4];
	int vm_stats_vm_v_active_count_mib[4];
	int vm_stats_vm_v_cache_count_mib[4];
	int vm_stats_vm_v_inactive_count_mib[4];
	int vfs_bufspace_mib[2];
	int kern_cp_time_mib[2];
	int kern_cp_times_mib[2];
} GlobalPlatformData;

#ifndef CLAMP
#define CLAMP(x,low,high) (((x)>(high))?(high):(((x)<(low))?(low):(x)))
#endif

extern GlobalPlatformData platform;

void Platform_init();

extern ProcessField Platform_defaultFields[];

extern const unsigned int Platform_numberOfFields;

extern const SignalItem Platform_signals[];

extern const unsigned int Platform_numberOfSignals;

void Platform_setBindings(Htop_Action* keys);

extern MeterClass* Platform_meterTypes[];

int Platform_getMaxPid();

double Platform_updateCPUValues(Meter *meter, int cpu);

void Platform_updateMemoryValues(Meter *meter);

void Platform_updateSwapValues(Meter *meter);

char **Platform_getProcessArgv(const Process *proc);

char **Platform_getProcessEnvv(const Process *proc);

bool Platform_haveSwap();

#endif
