/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_linux_Platform
#define HEADER_linux_Platform
/*
htop - linux/Platform.h
(C) 2014 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Action.h"
#include "MainPanel.h"
#include "BatteryMeter.h"
#include "SignalsPanel.h"

#ifndef CLAMP
#define CLAMP(x,low,high) (((x)>(high))?(high):(((x)<(low))?(low):(x)))
#endif

extern ProcessField Platform_defaultFields[];

extern const unsigned int Platform_numberOfFields;

extern const SignalItem Platform_signals[];

extern const unsigned int Platform_numberOfSignals;

void Platform_setBindings(Htop_Action* keys);

extern MeterClass* Platform_meterTypes[];

int Platform_getUptime();

void Platform_getLoadAverage(double* one, double* five, double* fifteen);

int Platform_getMaxPid();

double Platform_updateCPUValues(Meter *meter, int cpu);

void Platform_updateMemoryValues(Meter *meter);

void Platform_updateSwapValues(Meter *meter);

char **Platform_getProcessArgv(const Process *proc);

char **Platform_getProcessEnvv(const Process *proc);

bool Platform_haveSwap();

#endif
